FROM golang:1.21 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./
RUN go build -o echoproxy cmd/main.go

# Create the final image
FROM debian:bullseye-slim

WORKDIR /root/

COPY --from=builder /app/echoproxy /usr/local/bin/echoproxy
COPY ./config/config.example.json /root/config.json

ENV PORT=8080
CMD ["/usr/local/bin/echoproxy", "-config", "/root/config.json"]
